// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ImgValidationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void imgValidation() {
    driver.get("https://mingle-portal.ca1.inforcloudsuite.com/TRANSLINK_PRD");
    driver.manage().window().setSize(new Dimension(1050, 943));
    driver.findElement(By.cssSelector("h5")).click();
    driver.findElement(By.linkText("TransLink Azure AD - Infor PROD")).click();
    driver.findElement(By.cssSelector("#mhdrAppBtn > .nm-icons")).click();
    driver.findElement(By.cssSelector("#\\36 1ce359b-2bf4-4c8b-b0db-af8f4062a176-menu > #icdeskSClk")).click();
    driver.switchTo().frame(3);
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("#SQQDZEOGBZUU5X8M > .widget-content > div")).click();
    vars.put("win1662", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1662").toString());
    driver.findElement(By.cssSelector(".two")).click();
    driver.findElement(By.cssSelector(".x-tree-expander-over .x-tree-elbow-img")).click();
    driver.findElement(By.cssSelector(".x-grid-item-focused .x-tree-node-text")).click();
    driver.findElement(By.id("uxpicktriggerfield-1162-inputEl")).click();
    driver.findElement(By.id("uxpicktriggerfield-1162-trigger-trigger")).click();
    driver.findElement(By.id("uxpicktriggerfield-1162-inputEl")).sendKeys("C00-03-0303-001");
    driver.findElement(By.id("tab-1234")).click();
    driver.findElement(By.cssSelector(".file .x-tree-node-text")).click();
    driver.findElement(By.id("textfield-1396-inputEl")).click();
  }
}
